title: Ahmetcan GÃ¼vendiren

description: >-
  (Web|Mobile) developer and Linux elitist. IZTECH Computer Engineering student.
baseurl: ''
url: 'https://glacion.com'
minima:
  date_format: '%Y-%m-%d'
  logo: '/favicon/android-chrome-192x192.png'
  social_links:
    twitter: theglacion
    github: glacion
    linkedin: glacion
    telegram: glacion
    email: ahm@glacion.com
disqus:
  shortname: glacion-com
google-analytics: UA-136610903-1
show_excerpts: true
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
